name: FullKicked
version: 1.3
main: com.firesahc.main
commands:
    reload_fk:
        description: "Reload the config file"
        usage: /<command>
        permission: FullKicked.reload_fk
    whitelist:
        description: "List the current whitelist"
        usage: /<command>
        permission: FullKicked.whitelist
    add_whitelist:
        description: "Add player to the config file"
        usage: /<command> <player>
        permission: FullKicked.add_whitelist
    remove_whitelist:
        description: "Remove player from the config file"
        usage: /<command> <player>
        permission: FullKicked.remove_whitelist
permissions:
    FullKicked.reload_fk:
        default: op
    FullKicked.whitelist:
        default: op
    FullKicked.add_whitelist:
        default: op
    FullKicked.remove_whitelist:
        default: op